server:
  servlet:
    context-path: /atcrowdfunding
  port: 80
#中文乱码
#spring:
#    http:
#        encoding:
#            force: true
#            charset: GB2312
#            enabled: true

#库配置
database:
  atcrowdfunding:
    driver: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/atcrowdfunding?useSSL=false